name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    release:
        types: [created]

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - run: npm install
            - run: npm run lint
            - run: npm test

    publish:
        if: github.event_name == 'release'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  registry-url: "https://registry.npmjs.org/"
            - run: npm install
            - run: npm run lint
            - run: npm test
            - name: Publish to npm
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
